### ISSUE TITLE
Crashes with Swift 5.7 and Xcode14

### ISSUE THREAD

**Issue by obrhoff** [kean/Get#60] opened 2022-09-17 18:48 UTC
I'm seeing this crash with Get 1.0.3 on an iOS App (code got generated with CreateAPI).

<img width="774" alt="Screenshot 2022-09-17 at 20 46 48" src="https://user-images.githubusercontent.com/199578/190872097-599e159b-c46b-4347-919a-490132a835f8.png">

**Comment by kean** [comment] 2022-09-17 19:22
Are you implementing this method (`didCreateTask`) in your code? Which thread does it get called on?

**Comment by obrhoff** [comment] 2022-09-17 21:23
Those methods are not implemented. I will check next time, when I catch the crash. (it appears randomly)

**Comment by kean** [comment] 2022-09-21 00:18
Thanks for the report. I'm able to reproduce it.

I think it's because `didCreateTask`, unlike _all_ other delegate methods, is called synchronously on the callers thread, and _not_ on the session's delegate queue.

**Comment by kean** [comment] 2022-09-21 01:14
Fixed in [2.1.1](https://github.com/kean/Get/releases/tag/2.1.1)

**Closed by kean** 2022-09-21 01:14 UTC
Labels: bug

**Comment by obrhoff** [comment] 2022-09-22 10:06
Thanks for the fix. Unfortunately CreateAPI didn't move yet to v2. Would it be possible to backport the issue?

**Comment by kean** [comment] 2022-09-22 12:32
Yes, I created two patches, including [1.0.4](https://github.com/kean/Get/releases/tag/1.0.4) for 1.x.
